package casework

const (
	CaseStatusPendingAck           = "PENDING_ACK"
	CaseStatusAcknowledged         = "ACKNOWLEDGED"
	CaseStatusHandling             = "HANDLING"
	CaseStatusWaitingClient        = "WAITING_CLIENT"
	CaseStatusWaitingCollaboration = "WAITING_COLLABORATION"
	CaseStatusWaitingSupervisor    = "WAITING_SUPERVISOR"
	CaseStatusResolved             = "RESOLVED"
	CaseStatusClosed               = "CLOSED"

	CaseSourceRuleHit = "RULE_HIT"

	CaseActionAcknowledge = "ACKNOWLEDGE"
	CaseActionContact     = "CONTACT"
	CaseActionHandling    = "HANDLING"
	CaseActionEscalate    = "ESCALATE"
	CaseActionGuidance    = "GUIDANCE"
	CaseActionIntervene   = "INTERVENE"
	CaseActionResolve     = "RESOLVE"
	CaseActionClose       = "CLOSE"
	CaseActionReopen      = "REOPEN"

	ActionSourceSystem = "SYSTEM"
	ActionSourceStaff  = "STAFF"

	TodoCategoryContentAttention = "CONTENT_ATTENTION"
	TodoCategoryDeliveryIssue    = "DELIVERY_ISSUE"
	TodoCategoryConsultation     = "CONSULTATION"
	TodoSourceAttentionCase      = "ATTENTION_CASE"
	TodoSourceConsultation       = "CONSULTATION"
	TodoStatusOpen               = "OPEN"
	TodoStatusCompleted          = "COMPLETED"
	TodoStatusSuperseded         = "SUPERSEDED"
	TodoActiveSlot               = "ACTIVE"

	EventAttentionCaseOpened       = "AttentionCaseOpened"
	EventAttentionCaseAcknowledged = "AttentionCaseAcknowledged"
	EventAttentionHandlingRecorded = "AttentionHandlingRecorded"
	EventAttentionCaseEscalated    = "AttentionCaseEscalated"
	EventAttentionCaseResolved     = "AttentionCaseResolved"
	EventAttentionCaseClosed       = "AttentionCaseClosed"
	EventAttentionCaseReopened     = "AttentionCaseReopened"
	EventSupervisorGuidanceAdded   = "SupervisorGuidanceAdded"

	ConsultationSourceOnline = "ONLINE"

	ConsultationUrgencyRoutine   = "ROUTINE"
	ConsultationUrgencyExpedited = "EXPEDITED"

	ConsultationStatusNew                  = "NEW"
	ConsultationStatusWaitingAssignment    = "WAITING_ASSIGNMENT"
	ConsultationStatusAssigned             = "ASSIGNED"
	ConsultationStatusHandling             = "HANDLING"
	ConsultationStatusWaitingClient        = "WAITING_CLIENT"
	ConsultationStatusWaitingCollaboration = "WAITING_COLLABORATION"
	ConsultationStatusResolved             = "RESOLVED"
	ConsultationStatusClosed               = "CLOSED"

	ConsultationActorClient = "CLIENT"
	ConsultationActorStaff  = "STAFF"
	ConsultationActorSystem = "SYSTEM"

	ConsultationActionCreate        = "CREATE"
	ConsultationActionAssign        = "ASSIGN"
	ConsultationActionClientMessage = "CLIENT_MESSAGE"
	ConsultationActionReply         = "REPLY"
	ConsultationActionTransfer      = "TRANSFER"
	ConsultationActionEscalate      = "ESCALATE"
	ConsultationActionResolve       = "RESOLVE"
	ConsultationActionClose         = "CLOSE"
	ConsultationActionReopen        = "REOPEN"

	EventConsultationCreated      = "ConsultationCreated"
	EventConsultationAssigned     = "ConsultationAssigned"
	EventConsultationMessageAdded = "ConsultationMessageAdded"
	EventConsultationReplied      = "ConsultationReplied"
	EventConsultationTransferred  = "ConsultationTransferred"
	EventConsultationEscalated    = "ConsultationEscalated"
	EventConsultationResolved     = "ConsultationResolved"
	EventConsultationClosed       = "ConsultationClosed"
	EventConsultationReopened     = "ConsultationReopened"
)
